### ISSUE TITLE
Can't import the library

### ISSUE THREAD

**Issue by hyruuk** [neurosity/neurosity-python-sdk#6]
I am trying to run the example code with my newly acquired Neurosity Crown. I run Linux Mint 21.1 with mamba 1.4.1 and conda 23.1.0.

I created an environment with mamba : 
`mamba create -n neurosity_env python==3.9`
Then installed the package : 
`mamba activate neurosity_env
pip install neurosity`
Then I try to load the library in iPython : 
`pip install ipython
ipython
from neurosity import neurositySDK`

But it returns this error : 
```In [3]: from neurosity import neurositySDK
Traceback (most recent call last):

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3508 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[3], line 1
    from neurosity import neurositySDK

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/neurosity/__init__.py:2
    from neurosity.neurosity import neurosity_sdk

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/neurosity/neurosity.py:1
    import pyrebase

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/pyrebase/__init__.py:1
    from .pyrebase import initialize_app

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/pyrebase/pyrebase.py:17
    from oauth2client.service_account import ServiceAccountCredentials

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/oauth2client/service_account.py:25
    from oauth2client import client

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/oauth2client/client.py:47
    from oauth2client import crypt

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/oauth2client/crypt.py:55
    from oauth2client import _pycrypto_crypt

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/oauth2client/_pycrypto_crypt.py:17
    from Crypto.PublicKey import RSA

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/Crypto/PublicKey/__init__.py:29
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/Crypto/Util/asn1.py:33
    from Crypto.Util.number import long_to_bytes, bytes_to_long

  File ~/mambaforge/envs/neurosity/lib/python3.9/site-packages/Crypto/Util/number.py:398
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax
```

What am I doing wrong ? 

Thanks for your assistance :)

**Comment by tensoralex** [comment]
Try: `pip install pyrebase4`

`conda create -n neurosity_reproduce python=3.9
conda activate neurosity_reproduce

cd neurosity-python-sdk/

pip install -e .

….
Successfully built gcloud oauth2client pycryptodome jws
Installing collected packages: requests, pycryptodome, pyasn1, jws, six, rsa, requests-toolbelt, python-jwt, pyparsing, pyasn1-modules, protobuf, httplib2, googleapis-common-protos, oauth2client, gcloud, pyrebase, neurosity
  Running setup.py develop for neurosity
Successfully installed gcloud-0.17.0 googleapis-common-protos-1.58.0 httplib2-0.21.0 jws-0.1.3 neurosity-1.0.2 oauth2client-3.0.0 protobuf-4.22.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycryptodome-3.4.3 pyparsing-3.0.9 pyrebase-3.0.27 python-jwt-2.0.1 requests-2.11.1 requests-toolbelt-0.7.0 rsa-4.9 six-1.16.0

…
python
Python 3.9.16 (main, Mar  1 2023, 18:22:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from neurosity import neurosity_sdk

    from Crypto.PublicKey import RSA
  File "/home/alx/anaconda3/envs/neurosity_reproduce/lib/python3.9/site-packages/Crypto/PublicKey/__init__.py", line 29, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
  File "/home/alx/anaconda3/envs/neurosity_reproduce/lib/python3.9/site-packages/Crypto/Util/asn1.py", line 33, in <module>
    from Crypto.Util.number import long_to_bytes, bytes_to_long
  File "/home/alx/anaconda3/envs/neurosity_reproduce/lib/python3.9/site-packages/Crypto/Util/number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax
>>> exit()



pip install pyrebase4


python
Python 3.9.16 (main, Mar  1 2023, 18:22:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neurosity import neurosity_sdk
>>> `

**Comment by hyruuk** [comment]
That is strange, I cannot reproduce the previous error now (even from a fresh env).
I was able to install pyrebase4, but I now have an import error, is it related ? 

```(neurosity_env) hyruuk@laplin:~/GitHub/neurosity-python-sdk$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neurosity
>>> from neurosity import neurosity_sdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'neurosity_sdk' from 'neurosity' (/home/hyruuk/GitHub/neurosity-python-sdk/neurosity/__init__.py)
>>> from neurosity import neurositySDK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'neurositySDK' from 'neurosity' (/home/hyruuk/GitHub/neurosity-python-sdk/neurosity/__init__.py)
```
